### ISSUE TITLE
Make image format check case-insensitive (issues handling ".JPG" instead of ".jpg")

### ISSUE THREAD

**Issue by Simon-Dirks** [knaw-huc/loghi#15]
Running the pipeline on a larger dataset, I noticed that ".JPG" files were not processed, while ".jpg" files were processed correctly. Seems to me that this is handled [here](https://github.com/knaw-huc/laypa/blob/main/utils/input_utils.py) (I found the image formats [here](https://github.com/knaw-huc/laypa/blob/e57f8392eca3cb6638151616fedfd5155c697f99/run.py#L179)).

Can I ask to make the format check case-insensitive? I do not seem to be allowed to submit pull requests to the laypa repo.

**Comment by stefanklut** [comment]
Hey Simon,

Thanks for bringing this to our attention. I will be changing the formats in the next release to be case insensitive. We are likely also limiting the allowed formats to just jpeg/jpg and png. This too ensure that if something works on laypa it doesn't then break on loghi-tooling. If you are expecting to use other image formats please let us know so that we may gauge what formats need support.

You not being able to submit pull requests is of course not intended, could you tell me what error or message you get when trying to submit your pull request?

**Comment by Simon-Dirks** [comment]
Hi Stefan,

Great that you can incorporate this into the next release! Understandable to focus on just jpg/png. I believe we also have many PDFs in our dataset, but we can convert them using ImageMagick for now. I'm not sure if that should be part of the pipeline, though I can imagine it being really convenient not needing to do any preprocessing, especially when scaling to larger datasets.

Thanks for the awesome project!

**Comment by coret** [comment]
> I believe we also have many PDFs in our dataset (perhaps even some TIFFs or BMPs), but we can convert them using ImageMagick for now.

@Simon-Dirks yes, you can _convert_ PDF to images (or Extract PDF pages as images) using ImageMagick, but I think it's wiser to _extract_ the (often higher resolution) images from it's container, see https://commons.wikimedia.org/wiki/Commons:Extracting_images_from_PDF

**Comment by Simon-Dirks** [comment]
> > I believe we also have many PDFs in our dataset (perhaps even some TIFFs or BMPs), but we can convert them using ImageMagick for now.
> 
> @Simon-Dirks yes, you can _convert_ PDF to images (or Extract PDF pages as images) using ImageMagick, but I think it's wiser to _extract_ the (often higher resolution) images from it's container, see https://commons.wikimedia.org/wiki/Commons:Extracting_images_from_PDF

@coret Great idea, thanks!

**Comment by stefanklut** [comment]
Fixed with knaw-huc/laypa@082f087896a407b59f5a398420326d6af5f3fecd, keeping all image support for now as other people still requested tiff support. You can update to newest release for case insensitive support. PDF is considered for native support, but currently the manual extraction method sound like a good solution to your problem for now
